using G9MAUIControls.Icons;
using G9MAUIControls.Localization;
using G9MAUIControls.Theming;
using Maui.BindableProperty.Generator.Core;
using System.Windows.Input;

namespace G9MAUIControls.Controls;

/// <summary>
///     Search-flavored input — a thin specialization of <see cref="G9TextEntry" /> that
///     ships with the Material 3 search-bar defaults already configured:
///     <list type="bullet">
///         <item><see cref="G9OutlinedFieldBase.LeadingIcon" /> defaults to <see cref="G9Glyphs.Search" />.</item>
///         <item><see cref="G9TextEntry.ClearButton" /> defaults to <c>true</c>.</item>
///         <item><see cref="G9OutlinedFieldBase.Placeholder" /> defaults to a localized
///               "Search…" string.</item>
///     </list>
///     <para>
///         The control adds two search-specific behaviors that don't belong on the
///         general-purpose text entry:
///     </para>
///     <list type="number">
///         <item>
///             <b>Debounced query.</b> A debounce timer (<see cref="DebounceMs" />,
///             default 250 ms) starts on every <see cref="G9TextEntry.Text" /> change
///             and only fires <see cref="DebouncedTextChanged" /> + the
///             <see cref="SearchCommand" /> when the user has been still for the
///             debounce window. Avoids one-query-per-keystroke spam against the
///             underlying list / API. Set <see cref="DebounceMs" /> to <c>0</c> to
///             fire instantly with no debounce.
///         </item>
///         <item>
///             <b>Voice dictation ON by default.</b> The microphone itself is
///             <see cref="G9TextEntry.VoiceEnabled" /> on the base class (shared with
///             <c>G9Editor</c> through <see cref="G9VoiceDictation" />); a search box is simply the
///             one field in the suite that opts IN for you, because dictating a query is what
///             every system search bar offers. Set <c>VoiceEnabled="False"</c> on a field where
///             it does not belong — a typed barcode lookup, or a height-matched lane where the
///             extra trailing glyph is noise. Android speaks Persian directly via Google's
///             recognizer (<c>fa-IR</c>); iOS ships no Persian acoustic model in
///             <c>SFSpeechRecognizer</c>, so there the session reports a failure and Persian
///             users should use the keyboard's own dictation key.
///         </item>
///     </list>
/// </summary>
public partial class G9SearchEntry : G9TextEntry
{
    private IDispatcherTimer? _debounceTimer;

    /// <summary>
    ///     Debounce window for <see cref="DebouncedTextChanged" /> and
    ///     <see cref="SearchCommand" />. The default of 250 ms is the typical instant-search
    ///     sweet spot — short enough to feel responsive while typing, long enough to
    ///     coalesce a fast typist's keystrokes into a single query. Set to <c>0</c> to
    ///     disable debouncing and fire on every keystroke (e.g. when the underlying list
    ///     filter is purely client-side and cheap).
    /// </summary>
    [AutoBindable] private int _debounceMs;

    /// <summary>
    ///     Optional command bound to the search action. Fired with the current
    ///     <see cref="G9TextEntry.Text" /> as the parameter when the debounce window
    ///     elapses, OR immediately when the user taps the keyboard's "Search" return key.
    /// </summary>
    [AutoBindable] private ICommand? _searchCommand;

    public G9SearchEntry()
    {
        // M3 search-bar defaults. Set BEFORE the first apply pass so the constructor
        // chain ends with the user's overrides taking precedence — any consumer-set
        // value in XAML / code arrives via the AutoBindable setter AFTER the ctor runs
        // and naturally wins.
        LeadingIcon = G9Glyphs.Search;
        ClearButton = true;
        VoiceEnabled = true;
        DebounceMs = 250;
        Placeholder = G9Strings.Get(G9StringKey.Search);
        // A search box almost always sits at the top of a list / directly under a header, where the
        // floated label would otherwise overhang the field top and be covered by that element. Reserve
        // the clearance by default. Height-matched lanes (search beside sort/filter buttons) turn this
        // OFF to keep the shared centre line — see SearchSortFilterHeader / SamplingBatch / SamplesList.
        ReserveFloatingLabelClearance = true;

        // Observe Text via the bindable PropertyChanged pipeline. G9TextEntry's Text is
        // generated by [AutoBindable] which surfaces INotifyPropertyChanged; subscribing
        // here avoids the need for a public TextChanged event on the base class. This
        // also captures programmatic Text mutations (binding updates, Submit() calls
        // from code) so the debounce + SearchCommand fire consistently regardless of
        // how the value arrived.
        PropertyChanged += OnSearchPropertyChanged;
    }

    /// <summary>
    ///     Fired after <see cref="DebounceMs" /> have elapsed since the last keystroke
    ///     (or immediately when <see cref="DebounceMs" /> is 0 / on Search-key submit).
    ///     Cheaper alternative to a manual <see cref="G9TextEntry.Text" /> binding
    ///     subscription when the consumer wants instant-search semantics.
    /// </summary>
    public event EventHandler<string?>? DebouncedTextChanged;

    /// <summary>
    ///     Forces an immediate fire of <see cref="DebouncedTextChanged" /> /
    ///     <see cref="SearchCommand" /> with the current text — bypassing the debounce
    ///     window. Use when the user explicitly commits the query (Enter key, search
    ///     button, etc.).
    /// </summary>
    public void Submit()
    {
        StopDebounce();
        Fire(Text);
    }

    private void OnSearchPropertyChanged(object? sender, System.ComponentModel.PropertyChangedEventArgs e)
    {
        if (e.PropertyName != nameof(Text)) return;

        if (DebounceMs <= 0)
        {
            Fire(Text);
            return;
        }

        StopDebounce();
        _debounceTimer ??= Dispatcher.CreateTimer();
        _debounceTimer.Interval = TimeSpan.FromMilliseconds(DebounceMs);
        _debounceTimer.IsRepeating = false;
        _debounceTimer.Tick -= OnDebounceTick;
        _debounceTimer.Tick += OnDebounceTick;
        _debounceTimer.Start();
    }

    private void OnDebounceTick(object? sender, EventArgs e)
    {
        StopDebounce();
        Fire(Text);
    }

    private void StopDebounce()
    {
        if (_debounceTimer is null) return;
        if (_debounceTimer.IsRunning) _debounceTimer.Stop();
        _debounceTimer.Tick -= OnDebounceTick;
    }

    private void Fire(string? value)
    {
        DebouncedTextChanged?.Invoke(this, value);
        if (SearchCommand is { } cmd && cmd.CanExecute(value))
        {
            cmd.Execute(value);
        }
    }

    /// <summary>
    ///     A resting search box is ONE muted tone: its outline matches the placeholder
    ///     and the leading search glyph — <see cref="G9Palette.InputPlaceholder" /> — rather than the
    ///     generic <see cref="G9Palette.Outline" /> hairline every other outlined field rests on.
    ///     <para>
    ///         An empty search box is an invitation, not a form field with an answer in it. The
    ///         box read as multiple greys stacked on each other — border, icon, placeholder — which
    ///         is what this collapses into one.
    ///     </para>
    ///     <para>
    ///         Only the RESTING colour changes. Focus, a typed value, error and status states all
    ///         still resolve through the base, so a search box signals those exactly like every other
    ///         input in the app.
    ///     </para>
    /// </summary>
    protected override Color ResolveRestingOutlineColor(G9Palette palette) => palette.InputPlaceholder;

    /// <inheritdoc />
    protected override Color ResolveRestingContentColor(G9Palette palette) => palette.InputPlaceholder;
}
